### ISSUE TITLE
Requirements Gathering

### ISSUE THREAD

**Issue by AbdulrahmanAbozaid** [StudentPortal-grad/Documentations#2]
- [x] Review the Introduction and literature review and propose edits if needed
- [x] Surveys, questionnaires, interview etc.. 
- [x] Results of part (a) represented as charts
- [x] Discussion of results in part (b)

**Comment by nour-allam1412** [comment]
[Uploading Survey's Conclusion.pdf…]()

**Comment by nour-allam1412** [comment]
[Survey's Conclusion.pdf](https://github.com/user-attachments/files/18029397/Survey.s.Conclusion.pdf)
